### PR TITLE
Multisearch

### PR DESCRIPTION
**Pull request by mmacata**
This PR adds a multisearch to the client submodule.
Necessary for it is the basigx multisearch (https://github.com/terrestris/BasiGX/pull/111)
see also according PR in momo3-frontend

### CODE REVIEW

**Comment by annarieger** [comment]
Nice work, thanks a lot! :+1: 

Please adjust the `initialize-beans.xml` file for the other profiles (ci and production) as well. After that it can be merged.

**Comment by mmacata** [comment]
done for all 3 profiles.

**Comment by KaiVolland** [comment]
@mmacata & @annarieger should this be merged now?

**Comment by weskamm** [comment]
Yes it should, as the corresponding BasiGX PR has been merged, so ill merge now

**Pull request merged**
